sudo: false
language: node_js
node_js:
  # - "6"
  - "8"
  - "10"
  - "stable"

git:
  depth: 1

deploy:
    - provider: npm
      email: npmjs@newfututre.cc
      api_key: "${NPM_TOKEN}"
      skip_cleanup: true
      on:
          tags: true
          branch: master
          node_js: 'stable'