sudo: false
language: node_js
node_js:
  # - "6"
  - "8"
  - "10"
  - "stable"

git:
  depth: 1

before_deploy:
  - "[[ $TRAVIS_TAG == v* ]] || [[ $TRAVIS_TAG == V* ]]"
  - sed -i "s/^\(\W*version\W*\).*\(\W,\)$/\1${TRAVIS_TAG:1}\2/" package.json

deploy:
    - provider: npm
      email: npmjs@newfututre.cc
      api_key: "${NPM_TOKEN}"
      skip_cleanup: true
      on:
          tags: true
          branch: master
          node_js: 'stable'