name: beta

on:
  push:
    branches:
      - master

jobs:
  npm-beta:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          registry-url: https://registry.npmjs.org/
      - run: npm i
      - run: npm test
      - run: sed -i "s/^\(\W*postversion\W*\).*\(\W,\)$/\1cat CHANGELOG.md\2/" package.json
      - run: npm version prerelease --no-git-tag-version --no-commit-hooks --preid="beta.${GITHUB_SHA:0:5}"
      - run: npm publish --tag beta --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
