name: Publish NPM

on: [release]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - uses: actions/setup-node@v1
              with:
                  node-version: 12
            - run: npm i
            - run: npm test

    publish-npm:
        needs: build
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - uses: actions/setup-node@v1
            - run: '[[ $GITHUB_REF == refs/tags/v* ]] || [[ $GITHUB_REF == refs/tags/V* ]]'
            - run: 'sed -i "s/^\(\W*version\W*\).*\(\W,\)$/\1${GITHUB_REF:11}\2/" package.json'
              with:
                  node-version: 12
                  registry-url: https://registry.npmjs.org/
            - run: npm publish
              env:
                  NODE_AUTH_TOKEN: ${{secrets.npm_token}}

    publish-gpr:
        needs: build
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - uses: actions/setup-node@v1
              with:
                  node-version: 12
                  registry-url: https://npm.pkg.github.com/
                  scope: "@newfuture"
            - run: '[[ $GITHUB_REF == refs/tags/v* ]] || [[ $GITHUB_REF == refs/tags/V* ]]'
            - run: 'sed -i "s/^\(\W*version\W*\).*\(\W,\)$/\1${GITHUB_REF:11}\2/" package.json'
            - run: npm publish
              env:
                  NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
