name: ReleaseNPM

on:
    push:
        tags:
            - "v*"
            - "V*"

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - uses: actions/setup-node@v1
              with:
                  node-version: 12
            - run: npm i
            - run: npm test

    publish-npm:
        needs: build
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - name: publish to npm
              uses: actions/setup-node@v1
              with:
                  node-version: 12
                  registry-url: https://registry.npmjs.org/
            - run: npm publish
              env:
                  NODE_AUTH_TOKEN: ${{secrets.npm_token}}

    publish-gpr:
        needs: build
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - name: publish to github registry
              uses: actions/setup-node@v1
              with:
                  node-version: 12
                  registry-url: "https://npm.pkg.github.com"
                  scope: "@newfuture"
            - run: |
                  sed -i '0,/miniprogram-build/s/miniprogram-build/@newfuture\/&/' package.json
                  npm publish --access public
              env:
                  NPM_REGISTRY_URL: https://npm.pkg.github.com/
                  NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

    github-release:
        needs: build
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - name: Create github Release
              uses: Roang-zero1/github-create-release-action@v1.0.2
              env:
                  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
